// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using P21IntegrationWindowsService.Models;

namespace P21IntegrationWindowsService.Migrations
{
    [DbContext(typeof(ContactSyncContext))]
    partial class ContactSyncContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26");

            modelBuilder.Entity("P21IntegrationWindowsService.Models.ContactSync", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("P21_ID")
                        .HasColumnName("p21_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("PK_ID")
                        .HasColumnName("pk_id")
                        .HasColumnType("TEXT");

                    b.Property<string>("email_address")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("phone_number")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("sync_trigger_by")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("synced_on")
                        .HasColumnType("TEXT");

                    b.Property<string>("update_trigger_by")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updated_on")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("contactsync");
                });

            modelBuilder.Entity("P21IntegrationWindowsService.Models.Settings", b =>
                {
                    b.Property<int>("ICID")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("icid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Company")
                        .HasColumnName("company")
                        .HasColumnType("TEXT");

                    b.Property<int>("Frequency")
                        .HasColumnName("frequency")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnName("lastrun")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NextRun")
                        .HasColumnName("nextrun")
                        .HasColumnType("TEXT");

                    b.Property<string>("P21Url")
                        .HasColumnName("p21url")
                        .HasColumnType("TEXT");

                    b.Property<string>("SvcUrl")
                        .HasColumnName("svcurl")
                        .HasColumnType("TEXT");

                    b.HasKey("ICID");

                    b.ToTable("settings");
                });
#pragma warning restore 612, 618
        }
    }
}
